export const AUTH_TOKEN = "AUTH_TOKEN";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const UPDATE_ADMIN_PASSWORD = "UPDATE_ADMIN_PASSWORD";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";
export const NOTIFICATIONS = "NOTIFICATIONS";
export const NOTIFICATIONS_COUNT = "NOTIFICATIONS_COUNT";
export const CLOSE_NOTIFICATIONS = "CLOSE_NOTIFICATIONS";

export const BM_ALL_TASK = "BM_ALL_TASK";
export const BM_FAILURE = "BM_FAILURE";

export const RA_ALL_TASK = "RA_ALL_TASK";
export const RA_FAILURE = "RA_FAILURE";

export const CSC_ALL_TASK = "CSC_ALL_TASK";
export const CSC_FAILURE = "CSC_FAILURE";

export const FETCH_CUSTOMER = "FETCH_CUSTOMER";
export const FAIL_RESPONSE = "FAIL_RESPONSE";
export const STORE_USER_TOKEN = "STORE_USER_TOKEN";
